# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.srcs/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2.xci
# IP: The module: 'audio_recorder_axi_gpio_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.srcs/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2.xci
# IP: The module: 'audio_recorder_axi_gpio_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_recorder_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
