# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/audio_recorder.xdc

# Block Designs: bd/audio_recorder/audio_recorder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder || ORIG_REF_NAME==audio_recorder} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_processing_system7_0_2/audio_recorder_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_processing_system7_0_2 || ORIG_REF_NAME==audio_recorder_processing_system7_0_2} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_xbar_1/audio_recorder_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_xbar_1 || ORIG_REF_NAME==audio_recorder_xbar_1} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_ps7_0_axi_periph_1/audio_recorder_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_ps7_0_axi_periph_1 || ORIG_REF_NAME==audio_recorder_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_rst_ps7_0_100M_1/audio_recorder_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_rst_ps7_0_100M_1 || ORIG_REF_NAME==audio_recorder_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_zed_audio_ctrl_0_1/audio_recorder_zed_audio_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_zed_audio_ctrl_0_1 || ORIG_REF_NAME==audio_recorder_zed_audio_ctrl_0_1} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_axi_gpio_0_1/audio_recorder_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_axi_gpio_0_1 || ORIG_REF_NAME==audio_recorder_axi_gpio_0_1} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_axi_timer_0_0/audio_recorder_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_axi_timer_0_0 || ORIG_REF_NAME==audio_recorder_axi_timer_0_0} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_xlconcat_0_0/audio_recorder_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_xlconcat_0_0 || ORIG_REF_NAME==audio_recorder_xlconcat_0_0} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_axi_gpio_1_2/audio_recorder_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_axi_gpio_1_2 || ORIG_REF_NAME==audio_recorder_axi_gpio_1_2} -quiet] -quiet

# IP: bd/audio_recorder/ip/audio_recorder_auto_pc_0/audio_recorder_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_recorder_auto_pc_0 || ORIG_REF_NAME==audio_recorder_auto_pc_0} -quiet] -quiet

# XDC: s:/Documents/ENSC452/Milestone0/audio_recorder/audio_recorder.gen/sources_1/bd/audio_recorder/audio_recorder_ooc.xdc
